(deftheme lego
  "Created 2016-12-28.")

(custom-theme-set-faces
 'lego
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "gray" :slant normal))))
 '(minibuffer-prompt ((t (:foreground "violet"))))
 '(highlight ((t (:background "royal blue" :foreground "#202028"))))
 '(region ((t (:background "royal blue" :foreground "#202028"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "green"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "steel blue" :inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "steel blue"))))
 '(font-lock-constant-face ((t (:foreground "orange"))))
 '(font-lock-doc-face ((t (:foreground "violet"))))
 '(font-lock-function-name-face ((t (:foreground "forest green"))))
 '(font-lock-keyword-face ((t (:foreground "dark turquoise" :weight semi-bold))))
 '(font-lock-negation-char-face ((t (:foreground "orange red" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "gold" :slant italic :weight semi-bold))))
 '(font-lock-string-face ((t (:foreground "chocolate"))))
 '(font-lock-type-face ((t (:foreground "magenta1"))))
 '(font-lock-variable-name-face ((t (:foreground "yellow"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "light sea green" :underline t))))
 '(link-visited ((t (:inherit link :foreground "magenta3"))))
 '(fringe ((t (:background "#202028" :foreground "white"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "black" :foreground "white" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((default (:inherit (mode-line))) (((class color) (min-colors 88) (background light)) (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light)) (((class color) (min-colors 88) (background dark)) (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit (rainbow-delimiters-unmatched-face)))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "red" :weight extra-bold))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "purple1"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "light sea green"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "green"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "yellow"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "orange"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "red"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "chocolate"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "indian red"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "SeaGreen1"))))
 '(dired-directory ((t (:foreground "forest green" :weight semi-bold))))
 '(dired-flagged ((t (:foreground "red" :box (:line-width 2 :color "red" :style released-button)))))
 '(dired-ignored ((t (:foreground "gray40" :strike-through t))))
 '(dired-symlink ((t (:foreground "cyan" :slant italic :weight semi-bold))))
 '(org-level-1 ((t (:foreground "lime green" :height 1.5))))
 '(org-level-2 ((t (:foreground "gold" :weight semi-bold :height 1.3))))
 '(org-level-3 ((t (:foreground "dark turquoise" :weight semi-bold :height 1.2))))
 '(org-level-4 ((t (:foreground "DarkOrchid2" :height 1.1))))
 '(error ((t (:foreground "dark orange" :underline t :slant italic :weight bold))))
 '(git-gutter:modified ((t (:inherit default :foreground "SteelBlue1" :weight bold))))
 '(fic-face ((t (:foreground "dark orange" :box (:line-width 4 :style released-button) :slant italic :weight bold))))
 '(default ((t (:stipple nil :background "#202028" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(company-preview ((t (:background "forest green" :foreground "wheat"))))
 '(company-scrollbar-bg ((t (:background "dark orchid"))))
 '(company-scrollbar-fg ((t (:background "purple4"))))
 '(company-preview-common ((t (:foreground "gold" :inherit company-preview))))
 '(company-tooltip-common ((t (:foreground "purple4"))))
 '(company-tooltip ((t (:background "light sea green" :foreground "gold"))))
 '(company-tooltip-selection ((t (:background "forest green")))))

(provide-theme 'lego)
